### ISSUE TITLE
Design Proposal: Adjust Text size / Glyphs based on latitude

### ISSUE THREAD

**Issue by zerda-ocm** [maplibre/maplibre-style-spec#857] opened 2024-10-14 22:35 UTC
## Motivation

For a topological map in globe projection a consistent text size would improve the visual appeareance.

![text_scale_example](https://github.com/user-attachments/assets/f6da8bbf-86d1-4297-8d4e-5a599e5f56e2)

Texts appear smaller the closer they get to the poles. This can result in tapered labels, when a feature runs from north to south. For example a mountain range. This effect gets stronger closer to the poles.

## Proposed Change

```
"layout": {
    "text-projection": "globe" // or "mercator" as default
}
```

Each letter needs to be invidually scaled depending on latitude.

**Comment by HarelM** [comment] 2024-10-15 06:33
How would this proposal work with the other text manipulation abilities?
Mainly with `map` and `viewport` definition of [`text-pitch-aligment`](https://maplibre.org/maplibre-style-spec/layers/#text-pitch-alignment) and other text alignment and offsets?

**Comment by zerda-ocm** [comment] 2024-10-15 11:02
Layout properties that would result in individual letters to stay at a specific longitude/latitude should scale according to latitude:

Properties where this behaviour should apply:
- "text-rotation-alignment": "viewport-glyph" / "map"
- "text-pitch-alignment": "map"

Properties where this behaviour should not apply:
- "text-rotation-alignment": "viewport"
- "text-pitch-alignment": "viewport"

text alignments and offsets are affected depending on the properties above. For example with "text-pitch-alignment": "map":
- "text-justify": "right" (which might result in a shift north) -> glyphs get scaled up
- "text-offset": [1,1] -> a shift in latitude should scale the letters

**Comment by HarelM** [comment] 2024-10-22 06:48
It is still not clear (to me) how this would behave in all kind of possible scenarios.
Can you provide some visuals of how you'd expect this proposal to behave given the current possible configurations?

**Comment by zerda-ocm** [comment] 2024-10-22 12:18
Is there a specific combination that is unclear?

**Comment by HarelM** [comment] 2024-10-22 12:24
For me, all of them...

**Comment by zerda-ocm** [comment] 2024-10-22 13:30
Well, "all of them" might be a bit too much to visualize. Essentially, it boils down to one key point: if the text is projected on the map, it should maintain the same size regardless of its position on the map. Let’s take an extreme case with the current implementation:

- **Left image**: A text placed on a line at the equator with a text size of 14 is perfectly readable. However, the same text size on Greenland becomes unreadable.

- **Center image**: I had to increase the text size to 60 just to make it readable. Notice how the individual letters still shrink significantly as they approach the poles, and the spacing between the letters also decreases.

- **Right image**: Although the text size is back to 14, the text maintains a consistent, readable size with uniform spacing.

![text-projection](https://github.com/user-attachments/assets/a412b262-0f24-47fd-8dcb-76c0423a1371)

**Comment by HarelM** [comment] 2024-10-22 14:06
Can you please share a jsbin that reproduces this. I tend to think there are ways currently to achieve what you want or something close to it. If not, then we should be able to add some property to the existing one instead of adding yet another confusing property.

**Comment by zerda-ocm** [comment] 2024-10-22 14:50
Sure: https://jsbin.com/matafateha/1/edit?html,console,output

**Comment by zerda-ocm** [comment] 2024-10-22 14:54
sure: https://jsbin.com/macezum/edit?html,console,output

**Comment by zerda-ocm** [comment] 2024-10-22 16:35
I don't think it's possible to achieve this look without modifying the code. To get the result shown above, I had to calculate distances using the Haversine formula instead of Mercator (in [placeGlyphAlongLine](https://github.com/maplibre/maplibre-gl-js/blob/main/src/symbol/projection.ts)). Without this, I couldn't achieve consistent spacing and would also get slightly different anchor centers. Additionally, I had to slightly modify [symbol_sdf.vertex.glsl](https://github.com/maplibre/maplibre-gl-js/blob/main/src/shaders/symbol_sdf.vertex.glsl) to adjust the glyph sizes.

So, instead of _"text-projection": "globe"_, would you prefer something like _"text-pitch-alignment": "globe-map"_? (I'm open to other suggestions.)

**Comment by HarelM** [comment] 2024-10-22 19:57
Is the following what you are after?
![image](https://github.com/user-attachments/assets/480c4e90-4c97-4342-b92f-90b963d541b3)
I've added `"text-pitch-alignment": "viewport",` to your example basically.
https://jsbin.com/gabexamaga/1/edit?html,output

**Comment by HarelM** [comment] 2024-10-22 19:58
It's also worth noting, due to how globe works that when panning the map closes to the poles the zoom changes, so if you want to style something that will work for poles and everywhere else you need to be cautious about how you use the zoom.
See here:
https://github.com/maplibre/maplibre-gl-js/blob/main/developer-guides/globe.md

**Comment by zerda-ocm** [comment] 2024-10-22 20:22
> Is the following what you are after? ) I've added `"text-pitch-alignment": "viewport",` to your example basically. https://jsbin.com/gabexamaga/1/edit?html,output

It is close, but not quite there. I need the text to align with the map and not with the viewport:

![Screenshot 2024-10-22 221135](https://github.com/user-attachments/assets/d6f1a2d0-28bb-406c-819f-eb2bcd131b3f)

**Comment by HarelM** [comment] 2024-10-22 20:31
CC: @kubapelc - it is possible that there's an issue with the text close to the poles?
I'm not sure a new definition is actually needed here, feels like more in the realm of a bug...
I think that if the text size is defined as constant it should apply for text close to the poles as well...
But it might be something else.
If this is a bug I'll move it to the maplibre-gl-js repo.

**Comment by zerda-ocm** [comment] 2024-10-22 21:28
Whether it's an issue or a bug depends on your perspective:

It’s a feature if you want to maintain visual consistency between the Mercator and globe projections (the text may appear distorted, but its position remains consistent).

It’s a bug if you expect the text size to remain constant.

(Personally, I lean towards labeling this as a bug, but it's not for me to decide.)

**Comment by HarelM** [comment] 2024-10-29 14:55
I think the following bug described this issue, right?
- https://github.com/maplibre/maplibre-gl-js/issues/4786

**Comment by zerda-ocm** [comment] 2024-10-29 15:29
I would say it is related because it solves the issue with the text-size. However the spacings would still need some work;

![Screenshot 2024-10-29 162525](https://github.com/user-attachments/assets/dc54ad63-0d84-4832-bd49-6fb93e08a1d2)

**Comment by HarelM** [comment] 2024-10-29 15:32
I would suggest continueing the discussion in the other repo.
Closing this proposal.

**Closed by HarelM** 2024-10-29 15:32 UTC
Labels: enhancement
